# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='p_id')),
                ('post_text', models.TextField(verbose_name='p_text')),
                ('post_date', models.DateField(auto_now=True, verbose_name='p_date')),
                ('post_time', models.TimeField(auto_now=True, verbose_name='p_time')),
                ('post_like', models.IntegerField(default=0, verbose_name='p_like')),
                ('post_comments', models.IntegerField(default=0, verbose_name='p_comm')),
                ('post_dislike', models.IntegerField(default=0, verbose_name='p_dislike')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User')),
            ],
        ),
    ]
