# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20170806_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
        migrations.AddField(
            model_name='post',
            name='post_comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
