# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='u_id')),
                ('user_name', models.CharField(max_length=100, verbose_name='u_name')),
                ('user_password', models.CharField(max_length=100, verbose_name='u_pwd')),
                ('user_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, verbose_name='u_sex')),
                ('user_email', models.EmailField(max_length=50, verbose_name='u_email')),
                ('user_dob', models.DateField(verbose_name='u_dob')),
                ('user_joindate', models.DateTimeField(auto_now_add=True, verbose_name='u_join_date')),
            ],
        ),
    ]
