# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20170806_1304'),
        ('commentapp', '0003_auto_20170806_1304'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
