# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='c_id')),
                ('comment_text', models.CharField(max_length=200, verbose_name='c_text')),
                ('comment_datetime', models.DateTimeField(auto_now=True, verbose_name='c_datetime')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.Post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User')),
            ],
        ),
    ]
