# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0003_auto_20170806_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=200),
        ),
    ]
